---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: crystallang/crystal

inputs:
  - name: doge-weather
outputs:
  - name: build_code_output

run:
  path: sh
  args:
  - -exc
  - doge-weather/ci/scripts/build doge-weather build_code_output
