---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: crystallang/crystal
    tag: 0.20.1

inputs:
  - name: helionce-git-repo
  - name: custom-task-base
outputs:
  - name: build_code_output

run:
  path: sh
  args:
  - -exc
  - helionce-git-repo/hce-ci/scripts/build helionce-git-repo build_code_output
